version: "3"

services:

  #1 Nginx Server
  nginx_app:
    build: images/nginx
    volumes:
      - ./images/nginx/nginx.conf:/etc/nginx/conf.d/mysite.template
      - ./app:/var/www/html/app/
    ports:
      - '2000:80'
    environment:
      FPM: 'php_app:9000'
      ROOT: '/var/www/html/app/public'
    command: /bin/bash -c "envsubst '$$FPM $$ROOT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && cat /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  #2 Php fpm interpreter Service
  php_app:
    build:
      context: images/php
      args:
        PORT: 9000
    volumes:
      - ./app:/var/www/html/app/
    working_dir: /var/www/html/app
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db_app
      DB_DATABASE: lumen
      DB_USERNAME: root
      DB_PASSWORD: secret

  #3 Service DB
  db_app:
    image: mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: lumen

  phpmyadmin:
    depends_on:
      - db_app
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '2001:80'
    environment:
      PMA_HOST: db_app
      MYSQL_ROOT_PASSWORD: secret

volumes:
  rabbitmq-data:
    driver: local
